//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapCreator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string game_path {
            get {
                return ((string)(this["game_path"]));
            }
            set {
                this["game_path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool mapGenerateBackground {
            get {
                return ((bool)(this["mapGenerateBackground"]));
            }
            set {
                this["mapGenerateBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool mapGenerateHeightmap {
            get {
                return ((bool)(this["mapGenerateHeightmap"]));
            }
            set {
                this["mapGenerateHeightmap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("35")]
        public decimal mapHeightmapZScale {
            get {
                return ((decimal)(this["mapHeightmapZScale"]));
            }
            set {
                this["mapHeightmapZScale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public decimal mapHeightmapMinLight {
            get {
                return ((decimal)(this["mapHeightmapMinLight"]));
            }
            set {
                this["mapHeightmapMinLight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.5")]
        public decimal mapHeightmapMaxLight {
            get {
                return ((decimal)(this["mapHeightmapMaxLight"]));
            }
            set {
                this["mapHeightmapMaxLight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal mapHeightmapZVector1 {
            get {
                return ((decimal)(this["mapHeightmapZVector1"]));
            }
            set {
                this["mapHeightmapZVector1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal mapHeightmapZVector2 {
            get {
                return ((decimal)(this["mapHeightmapZVector2"]));
            }
            set {
                this["mapHeightmapZVector2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public decimal mapHeightmapZVector3 {
            get {
                return ((decimal)(this["mapHeightmapZVector3"]));
            }
            set {
                this["mapHeightmapZVector3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool mapGenerateRivers {
            get {
                return ((bool)(this["mapGenerateRivers"]));
            }
            set {
                this["mapGenerateRivers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 64, 128")]
        public global::System.Drawing.Color mapRiverColor {
            get {
                return ((global::System.Drawing.Color)(this["mapRiverColor"]));
            }
            set {
                this["mapRiverColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mapRiverColorUseDefault {
            get {
                return ((bool)(this["mapRiverColorUseDefault"]));
            }
            set {
                this["mapRiverColorUseDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public decimal mapRiverOpacity {
            get {
                return ((decimal)(this["mapRiverOpacity"]));
            }
            set {
                this["mapRiverOpacity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool mapGenerateBounds {
            get {
                return ((bool)(this["mapGenerateBounds"]));
            }
            set {
                this["mapGenerateBounds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color mapBoundsColor {
            get {
                return ((global::System.Drawing.Color)(this["mapBoundsColor"]));
            }
            set {
                this["mapBoundsColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("65")]
        public decimal mapBoundsOpacity {
            get {
                return ((decimal)(this["mapBoundsOpacity"]));
            }
            set {
                this["mapBoundsOpacity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2048")]
        public decimal mapWidth {
            get {
                return ((decimal)(this["mapWidth"]));
            }
            set {
                this["mapWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool mapDrawBuildings {
            get {
                return ((bool)(this["mapDrawBuildings"]));
            }
            set {
                this["mapDrawBuildings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool mapDrawTrees {
            get {
                return ((bool)(this["mapDrawTrees"]));
            }
            set {
                this["mapDrawTrees"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("000")]
        public string lastCreatedMaps {
            get {
                return ((string)(this["lastCreatedMaps"]));
            }
            set {
                this["lastCreatedMaps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool removeBoundsFromMap {
            get {
                return ((bool)(this["removeBoundsFromMap"]));
            }
            set {
                this["removeBoundsFromMap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool treesAsShadedModel {
            get {
                return ((bool)(this["treesAsShadedModel"]));
            }
            set {
                this["treesAsShadedModel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool treesAsImages {
            get {
                return ((bool)(this["treesAsImages"]));
            }
            set {
                this["treesAsImages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("JPEG")]
        public string mapType {
            get {
                return ((string)(this["mapType"]));
            }
            set {
                this["mapType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public decimal mapQuality {
            get {
                return ((decimal)(this["mapQuality"]));
            }
            set {
                this["mapQuality"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("zone{id}_{size}")]
        public string mapFilePattern {
            get {
                return ((string)(this["mapFilePattern"]));
            }
            set {
                this["mapFilePattern"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string shapedNifLastFile {
            get {
                return ((string)(this["shapedNifLastFile"]));
            }
            set {
                this["shapedNifLastFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public decimal mapTreeTransparency {
            get {
                return ((decimal)(this["mapTreeTransparency"]));
            }
            set {
                this["mapTreeTransparency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("maps")]
        public string targetDirectoryPattern {
            get {
                return ((string)(this["targetDirectoryPattern"]));
            }
            set {
                this["targetDirectoryPattern"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool skipIfFileExists {
            get {
                return ((bool)(this["skipIfFileExists"]));
            }
            set {
                this["skipIfFileExists"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string targetMapPath {
            get {
                return ((string)(this["targetMapPath"]));
            }
            set {
                this["targetMapPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool enableResultPreview {
            get {
                return ((bool)(this["enableResultPreview"]));
            }
            set {
                this["enableResultPreview"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool enableLog {
            get {
                return ((bool)(this["enableLog"]));
            }
            set {
                this["enableLog"] = value;
            }
        }
    }
}
